apps/publicaciones/urls.py
from django.urls import path
from django.views.decorators.http import require_POST
from . import views

app_name = 'publicaciones'

urlpatterns = [
   path('', views.IndexListView.as_view(), name = 'home'),
   path('ver/<int:pk>', views.PublicacionesDetailView.as_view(), name = 'ver'),
   path('publicar/', views.Nueva_Publicacion.as_view(), name = 'nueva_publicacion'),
   path('editar/<int:pk>', views.Editar_Publicacion.as_view(), name = 'editar_publicacion'),
   path('eliminar/<int:pk>', views.Eliminar_Publicacion.as_view(), name = 'eliminar_publicacion'),
   path('publicaciones/', views.Mis_Publicaciones.as_view(), name = 'mis_publicaciones'),
   path('buscar/', views.BuscarListView.as_view(), name = 'buscar'),
   path('categoria/<int:pk>', views.PubCatListView.as_view(), name = 'publicaciones_categoria'),
   path('comentar/<int:pk>', require_POST(views.Nuevo_Comentario.as_view()), name = 'comentar'),
]

tpfinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.publicaciones.urls')),
    path('', include('apps.usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/templatetags/menu_categorias.html
<a class="nav-link dropdown-toggle" href="#" id="categoriaDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
    Categorías
</a>
<ul class="dropdown-menu" aria-labelledby="categoriaDropdown">
    {% for c in categorias %}
        <li>
            <a class="dropdown-item" href="{% url 'publicaciones:publicaciones_categoria' c.id %}">{{c.nombre}}</a>
        </li>
    {% endfor %}
</ul>