apps/publicaciones/urls.py
from django.urls import path
from django.views.decorators.http import require_POST
from . import views

app_name = 'publicaciones'

urlpatterns = [
   path('', views.IndexListView.as_view(), name = 'home'),
   path('ver/<int:pk>', views.PublicacionesDetailView.as_view(), name = 'ver'),
   path('publicar/', views.Nueva_Publicacion.as_view(), name = 'nueva_publicacion'),
   path('editar/<int:pk>', views.Editar_Publicacion.as_view(), name = 'editar_publicacion'),
   path('eliminar/<int:pk>', views.Eliminar_Publicacion.as_view(), name = 'eliminar_publicacion'),
   path('publicaciones/', views.Mis_Publicaciones.as_view(), name = 'mis_publicaciones'),
   path('buscar/', views.BuscarListView.as_view(), name = 'buscar'),
   path('categoria/<int:pk>', views.PubCatListView.as_view(), name = 'publicaciones_categoria'),
   path('comentar/<int:pk>', require_POST(views.Nuevo_Comentario.as_view()), name = 'comentar'),
]

tpfinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.publicaciones.urls')),
    path('', include('apps.usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/publicacion/buscar.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Buscar</h1>

<form action="{% url 'publicaciones:buscar' %}" method="GET" enctype="multipart/form-data" autocomplete="off">
    {{ form.as_p }}
    <div class="form-group mt-4">
        <button class="btn btn-outline-info" type="submit">Buscar</button>
    </div>
</form>

<hr/>

{% for p in publicaciones %}
    <div class="row mb-5">
        <div class="col-md-3">
            <img src="{{p.imagen.url}}" alt="{{p.titulo}}" style="width: 100%;" class="img-thumbnail" />
        </div>
        <div class="col-md-9">
            <h3><a href="{% url 'publicaciones:ver' p.id %}">{{p.titulo}}</a></h3>
            <dl>
                <dt>{{p.categoria}}</dt>
                <dd>{{p.autor.first_name}} {{p.autor.last_name}} - {{p.fecha}}</dd>
            </dl>
            <p>{{p.descripcion}}</p>
        </div>
    </div>
{% endfor %}

{% endblock content %}

templates/publicacion/confirmar.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="border-bottom pb-2 mb-4">Eliminar publicación</h1>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %} 
            <p>Está seguro que desea eliminar la publicación "{{ object }}"?</p> 
            <div class="form-group mt-4">
                <button class="btn btn-outline-info" type="submit">Confirmar</button>
            </div>
        </form> 
    </div>
{% endblock content %}

templates/publicacion/editar.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="border-bottom pb-2 mb-4">Editar publicación</h1>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table> {{ form.as_table }} </table>
            <div class="form-group mt-4">
                <button class="btn btn-outline-info" type="submit">Guardar</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/publicacion/index.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2 class="mb-5"><i>Bienvenidos a la tienda donde tus sueños dulces se hacen realidad</i></h2>

{% for p in publicaciones %}
    <div class="row mb-5">
        <div class="col-md-3">
            <img src="{{p.imagen.url}}" alt="{{p.titulo}}" style="width: 100%;" class="img-thumbnail" />
        </div>
        <div class="col-md-9">
            <h3><a href="{% url 'publicaciones:ver' p.id %}">{{p.titulo}}</a></h3>
            <dl>
                <dt>{{p.categoria}}</dt>
                <dd>{{p.autor.first_name}} {{p.autor.last_name}} - {{p.fecha}}</dd>
            </dl>
            <p>{{p.descripcion}}</p>
        </div>
    </div>
{% endfor %}

{% endblock content %}

templates/publicacion/listar.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h1>Filtrar</h1>

{% for p in publicaciones %}
    <div class="row mb-5">
        <div class="col-md-3">
            <img src="{{p.imagen.url}}" alt="{{p.titulo}}" style="width: 100%;" class="img-thumbnail" />
        </div>
        <div class="col-md-9">
            <h3><a href="{% url 'publicaciones:ver' p.id %}">{{p.titulo}}</a></h3>
            <dl>
                <dt>{{p.categoria}}</dt>
                <dd>{{p.autor.first_name}} {{p.autor.last_name}} - {{p.fecha}}</dd>
            </dl>
            <p>{{p.descripcion}}</p>
        </div>
    </div>
{% endfor %}

{% endblock content %}

templates/publicacion/mispublicaciones.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<h2 class="mb-5">Mis publicaciones</h2>

{% for p in publicaciones %}
    <div class="row mb-5">
        <div class="col-md-3">
            <img src="{{p.imagen.url}}" alt="{{p.titulo}}" style="width: 100%;" class="img-thumbnail" />
        </div>
        <div class="col-md-9">
            <a href="{% url 'publicaciones:ver' p.id %}" class="d-inline-block"><h3>{{p.titulo}}</h3></a> 
            <a href="{% url 'publicaciones:editar_publicacion' p.id %}">[Editar]</a>
            <a href="{% url 'publicaciones:eliminar_publicacion' p.id %}">[Eliminar]</a>
            <dl>
                <dt>{{p.categoria}}</dt>
                <dd>{{p.autor.first_name}} {{p.autor.last_name}} - {{p.fecha}}</dd>
            </dl>
            <p>{{p.descripcion}}</p>
        </div>
    </div>
{% endfor %}

{% endblock content %}

templates/publicacion/nueva.html
{% extends 'base.html' %}

{% block content %}
    <h1 class="border-bottom pb-2 mb-4">Cargar publicacion</h1>
    <div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <table> {{ form.as_table }} </table>
            <div class="form-group mt-4">
                <button class="btn btn-outline-info" type="submit">Guardar</button>
            </div>
        </form>
    </div>
{% endblock content %}

templates/publicacion/ver.html
{% extends 'base.html' %}

{% block content %}

<h1><a href="{% url 'publicaciones:ver' publicacion.id %}">{{ publicacion.titulo }}</a></h1>
<img src="{{publicacion.imagen.url}}" alt="{{publicacion.titulo}}" style="width: 100%;" class="img-thumbnail" />
<dl>
  <dt>{{publicacion.categoria}}</dt>
  <dd>{{publicacion.autor.first_name}} {{publicacion.autor.last_name}} - {{publicacion.fecha}}</dd>
</dl>
<p>{{publicacion.descripcion}}</p>
<p>{{publicacion.contenido}}</p>
<div>
  <hr/>
  <h4>Comentarios</h4>
  <div class="comments-list">
    {% for c in comentarios %}
      <div class="media">
        <hr/>
        <p class="pull-right"><small>{{c.fecha}}</small></p>
        <a class="media-left" href="#">
          <img src="{{c.usuario.imagen.url}}" alt="{{c.usuario.username}}" style="width: 50px;height: 50px;" class="img-thumbnail" />
        </a>
        <div class="media-body">
          <h4 class="media-heading user_name">{{c.usuario.first_name}} {{c.usuario.last_name}}</h4>
          {{c.contenido}}
        </div>
      </div>
    {% endfor %}
  </div>
  {% if user.is_authenticated %}
  <hr/>
  <form action="{% url 'publicaciones:comentar' publicacion.id %}" method="POST" enctype="multipart/form-data" autocomplete="off">
    {% csrf_token %}
    {{ form.as_p }}
    <div class="form-group mt-4">
      <button class="btn btn-outline-info" type="submit">Comentar</button>
    </div>
  </form>
  {% endif %}
</div>
{% endblock content %}