apps/publicaciones/urls.py
from django.urls import path
from django.views.decorators.http import require_POST
from . import views

app_name = 'publicaciones'

urlpatterns = [
   path('', views.IndexListView.as_view(), name = 'home'),
   path('ver/<int:pk>', views.PublicacionesDetailView.as_view(), name = 'ver'),
   path('publicar/', views.Nueva_Publicacion.as_view(), name = 'nueva_publicacion'),
   path('editar/<int:pk>', views.Editar_Publicacion.as_view(), name = 'editar_publicacion'),
   path('eliminar/<int:pk>', views.Eliminar_Publicacion.as_view(), name = 'eliminar_publicacion'),
   path('publicaciones/', views.Mis_Publicaciones.as_view(), name = 'mis_publicaciones'),
   path('buscar/', views.BuscarListView.as_view(), name = 'buscar'),
   path('categoria/<int:pk>', views.PubCatListView.as_view(), name = 'publicaciones_categoria'),
   path('comentar/<int:pk>', require_POST(views.Nuevo_Comentario.as_view()), name = 'comentar'),
]

apps/usuarios/urls.py
from django.urls import path
from django.contrib.auth import views as auth
from . import views

app_name = 'usuarios'

urlpatterns = [
	path('emprendedores/', views.UsuEmpListView.as_view(), name = 'emprendedores'),
	path('perfil/', views.perfil.as_view(), name='perfil'),
    path('registro/', views.registro.as_view(), name='registro'),
    path('login/', auth.LoginView.as_view(template_name="usuarios/login.html"), name="login"),
    path('logout/', auth.LogoutView.as_view(), name="logout")
]

tpfinal/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),

    path('', include('apps.publicaciones.urls')),
    path('', include('apps.usuarios.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

templates/base.html
<!DOCTYPE html>
{% load static tags %}
<html>
  <head>
    <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" />
    <script type="text/javascript" src="{% static 'js/bootstrap.min.js' %}"></script>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <title>Bake Shop</title>
  </head>
  <body>
    <header style="background-color: #9badea;color: rgb(255, 255, 255);">
      <div class="container">
        <div class="row py-4">
          <div class="col-sm-3">
            <a href="{% url 'publicaciones:home' %}" class="navbar-brand d-inline-block p-0" style="color: white;">
              <h1>BAKE SHOP</h1>
            </a>
          </div>
          <div class="col-sm-6 py-1">
            <form action="{% url 'publicaciones:buscar' %}" class="d-flex">
              <input class="form-control me-2" type="search" name="q" placeholder="Buscar" aria-label="Buscar">
              <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
          </div>
          <div class="col-sm-3 text-end">
            {% if user.is_authenticated %}
            <div class="nav-item dropdown ml-auto">
              <div class="d-inline-block">
                <a class="nav-link dropdown-toggle" href="#" id="userDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false" style="color: white;">
                  <span>Hola {{user.username}}</span>
                </a>
                <ul class="dropdown-menu" aria-labelledby="userDropdown">
                  <li>
                    <a class="dropdown-item" href="{% url 'publicaciones:nueva_publicacion'%}">Nueva Publicación</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'publicaciones:mis_publicaciones'%}">Mis Publicaciones</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="{% url 'usuarios:perfil'%}">Perfil</a>
                  </li>
                  <li><hr class="dropdown-divider"></li>
                  <li>
                    <a class="dropdown-item" href="{% url 'usuarios:logout'%}">Cerrar sesión</a>
                  </li>
                </ul>
              </div>
            </div>
            {% else %}
            <a href="{% url 'usuarios:login'%}" style="color: white;">Iniciar sesión</a> / 
            <a href="{% url 'usuarios:registro'%}" style="color: white;">Registrarse</a>
            {% endif %}
          </div>
        </div>
      </div>
      <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class="container">
          <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100">
              <li class="nav-item">
                <a class="nav-link active" aria-current="page" href="{% url 'publicaciones:home' %}">Inicio</a>
              </li>
              <li class="nav-item mx-auto">
                <a class="nav-link" href="{% url 'usuarios:emprendedores' %}">Conoce a nuestros emprendedores</a>
              </li>
              <li class="nav-item dropdown ml-auto">
                {% menu_categorias %}
              </li>
              {% if request.resolver_match.url_name in 'home,buscar,publicaciones_categoria,mis_publicaciones' %}
              <li class="nav-item dropdown ml-auto">
                <a class="nav-link dropdown-toggle" href="#" id="ordenDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                  Ordenar
                </a>
                <ul class="dropdown-menu" aria-labelledby="ordenDropdown">
                  <li>
                    <a class="dropdown-item" href="?{% url_replace request 'orden' 'desc' %}">Más nuevos primero</a>
                  </li>
                  <li>
                    <a class="dropdown-item" href="?{% url_replace request 'orden' 'asc' %}">Más viejos primero</a>
                  </li>
                </ul>
              </li>
              {% endif %}
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main>
      <div class="container py-5"> 
        {% block content %} {% endblock %}
      </div>
    </main>
    <footer style="background-color: #9badea;color: rgb(255, 255, 255);">
      <div class="container">
        <div class="py-4">
          <h3>BAKE SHOP</h3>
          <p>
            ¿Querés unirte a nuestra comunidad?
            <br>Ayudamos a potenciar tu marca
            <br><a href="mailto:bake_shop@gmail.com" title="Enviar email a Bake shop">Contactanos</a> 
          </p>
          <p>
            <img src="{% static 'imagenes/face.png' %}" width="20" height="20">
            <img src="{% static 'imagenes/instagram.png' %}" width="20" height="20">
            <img src="{% static 'imagenes/correo.png' %}" width="20" height="20">
          </p>
        </div>
        <div class="pb-5 text-center">
          Derechos Reservados 2021 © <strong>BAKE SHOP</strong>.
        </div>
      </div>
    </footer>
  </body>
</html>

templates/prueba.html
{% extends 'base.html' %}

{% block content %}

HOME <br/>

<a href="{% url 'productos:listar' %}">Listar Productos</a>
<a href="{% url 'productos:cargar_p' %}">Cargar Productos</a>
<a href="{% url 'productos:cargar_r' %}">Cargar Rubro</a>

{% endblock content %}